project_name: helm-gopg

before:
  hooks:
    - go mod download

builds:
- id: helm-gopg
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s
    - -w
    - -X krishnaiyer.dev/golang/helm-gopg/cmd.version={{.Version}}
    - -X krishnaiyer.dev/golang/helm-gopg/cmd.gitCommit={{.Commit}}
    - -X krishnaiyer.dev/golang/helm-gopg/cmd.buildDate={{.Date}}
  goos: [darwin, linux, windows]
  goarch: [ "386", amd64, arm, arm64]
  ignore:
    - { goos: darwin, goarch: "386" }

archives:
- id: tar
  builds:
    - helm-gopg
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
  files:
    - LICENSE
    - README.md
  format: tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
