name: test
on:
  push:
    paths:
      - '**.go'

jobs:
  test:
    name: buildandtest
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '~1.19'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download dependencies
      run: make deps
    - name: Run package tests
      run: make test
